apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hgf
  template:
    metadata:
      labels:
        app: hgf
    spec:
      containers:
      - image: okteto.dev/hgf:latest
        name: hgf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0542e4ad-eb9f-4fd5-8615-cc7a88dc9883"
        - name: Vless_Path
          value: "/vdf6c"
        - name: Vmess_UUID
          value: "0542e4ad-eb9f-4fd5-8615-cc7a88dc9883"
        - name: Vmess_Path
          value: "/uhy9mn"
        - name: Share_Path
          value: "/v2link"
